version: '3'
services:
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
      - LOCAL=true
    expose:
      - "8080"
      - "5432"
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "nakama"]
      interval: 1s
      timeout: 1s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts/db/:/docker-entrypoint-initdb.d
  
  chain-chomp:
    build: ./
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - LOCAL=true
      - WEB3_CHAIN=base_sepolia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localdb
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    expose:
      - 10999
    ports:
      - "10999:10999"
volumes:
  data:
